backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "/img"
locale: "nl"
logo_url: "/files/logo.png"

collections: # A list of collections the CMS should be able to edit
  - name: "nieuws" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Nieuws en activiteiten" # Used in the UI, ie.: "New Post"
    folder: "site/content/nieuws" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Nieuwsdatum", name: "date", widget: "datetime"}
      - {label: "Introductietekst", name: "description", widget: "text"}
      - {label: "Hoofdafbeelding", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Download", name: "download", widget: "file", required: false}
      - label: "Afbeeldingen"
        name: images
        widget: list
        required: false
        fields:
          - { label: "Afbeelding", name: "image", widget: "image" }
  - name: "teams"
    label: "Teams"
    folder: "site/content/teams"
    create: true
    fields:
      - {label: "Teamnaam", name: "title", widget: "string"}
      - {label: "Categorie", name: "category", widget: "select", options: ["junior", "heren", "dames"]}
      - {label: "Teamfoto", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Download", name: "download", widget: "file", required: false}
  - name: "pages"
    label: "Pagina's"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Titel, name: title, widget: string}
          - label: "Notificatie"
            name: blurb
            widget: object
            fields:
              - {label: "Kop", name: "heading", widget: string}
              - {label: "Tekst", name: "text", widget: "text"}
      - file: "site/content/clubinfo.md"
        label: "Clubinfo"
        name: "clubinfo"
        fields:
          - {label: Titel, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: "Download", name: "download", widget: "file", required: false}
      - file: "site/content/lidmaatschap.md"
        label: "Lidmaatschap"
        name: "lidmaatschap"
        fields:
          - {label: Titel, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: "Download", name: "download", widget: "file", required: false}
      - file: "site/content/oud-papier.md"
        label: "Oud papier"
        name: "oud-papier"
        fields:
          - {label: Titel, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: "Download", name: "download", widget: "file", required: false}
      - file: "site/content/privacy.md"
        label: "Privacy"
        name: "privacy"
        fields:
          - {label: Titel, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: "Download", name: "download", widget: "file", required: false}
      - file: "site/content/supportersvereniging.md"
        label: "Supportersvereniging"
        name: "supportersvereniging"
        fields:
          - {label: Titel, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: "Download", name: "download", widget: "file", required: false}
      - file: "site/content/afgelastingen.md"
        label: "Afgelastingen"
        name: "afgelastingen"
        fields:
          - {label: Titel, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: "Download", name: "download", widget: "file", required: false}
      - file: "site/content/contact/_index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: Titel, name: title, widget: string}
          - {label: Afbeelding, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact regels
            name: contact_entries
            widget: list
            fields:
              - label: Kop
                name: heading
                widget: string
              - label: Tekst
                name: text
                widget: string
              - label: E-mailadres
                name: email
                widget: string
              - label: Telefoonnummer
                name: telephone
                widget: string
      - file: "site/content/routebeschrijving/_index.md"
        label: "Routebeschrijving"
        name: "routebeschrijving"
        fields:
          - {label: Titel, name: title, widget: string}
          - {label: Afbeelding, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/sponsors/_index.md"
        label: "Sponsoring"
        name: "sponsors"
        fields:
          - {label: Titel, name: title, widget: string}
          - { label: Body, name: body, widget: markdown }
          - label: "Topsponsor"
            name: top
            widget: list
            fields:
            - { label: "Afbeelding", name: "image", widget: "image" }
          - label: "Kleding"
            name: clothing
            widget: list
            fields:
            - { label: "Afbeelding", name: "image", widget: "image" }
          - label: "Reclamebord"
            name: boarding
            widget: list
            fields:
            - { label: "Afbeelding", name: "image", widget: "image" }
          - label: "Wedstrijdbal"
            name: ball
            widget: list
            fields:
            - { label: "Afbeelding", name: "image", widget: "image" }
          - label: "Materiaalsponsor"
            name: materials
            widget: list
            fields:
            - { label: "Afbeelding", name: "image", widget: "image" }
          - label: "Websitesponsor"
            name: website
            widget: list
            fields:
            - { label: "Afbeelding", name: "image", widget: "image" }
          - label: "Kantinesponsor"
            name: canteen
            widget: list
            fields:
            - { label: "Afbeelding", name: "image", widget: "image" }
